name: Check formatting
on:
  merge_group:
  push:
    branches:
      - 'main'
      - 'stable-*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/setup-node@v4.1.0

      - name: Set up Javascript environment
        uses: ./.github/actions/setup-javascript

      - name: Check formatting with Prettier
        run: yarn format:check
